---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: haproxy-ingress.rules
  labels:
    role: alert-rules
spec:
  groups:
  - name: haproxy-ingress.rules
    rules:
    # Frontend Session Usage (% of limit) | Warning
    - alert: HAProxyFrontendSessionsUsage
      expr: >-
        sum by (frontend) (haproxy_frontend_current_sessions)
        / sum by (frontend) (haproxy_frontend_limit_sessions)
        * 100 >= 80
      labels:
        severity: warning
      annotations:
        summary: "HAProxy: Session usage on {{ $labels.frontend }} frontend has reached {{ $value }}%"
        description: >-
          This alert will trigger when session usage is >= 80%.
        runbook_url: https://gitlab.com/mintel/satoshi/monitoring/runbooks/blob/master/satoshi/platform/HAProxy.md#HAProxyFrontendSessionUsage

    # Frontend Session Usage (% of limit) | Critical
    - alert: HAProxyFrontendSessionsUsage
      expr: >-
        sum by (frontend) (haproxy_frontend_current_sessions)
        / sum by (frontend) (haproxy_frontend_limit_sessions)
        * 100 >= 90
      labels:
        severity: critical
      annotations:
        summary: "HAProxy: Session usage on {{ $labels.frontend }} frontend has reached {{ $value }}%"
        description: >-
          This alert will trigger when session usage is >= 90%.
        runbook_url: https://gitlab.com/mintel/satoshi/monitoring/runbooks/blob/master/satoshi/platform/HAProxy.md#HAProxyFrontendSessionUsage

    # Frontend Requests Denied (% increase) not required. No ACLs currently configured in HAProxy.

    # Frontend Request Errors (% difference between 15m rate and 1m rate)
    - alert: HAProxyFrontendRequestsErrors
      expr: >-
        ( (
            sum by (frontend) (rate(haproxy_frontend_request_errors_total[1m]) +1)
            /
            sum by (frontend) (rate(haproxy_frontend_request_errors_total[15m]) +1)
          ) -1 ) * 100 > 2
      for: 5m
      annotations:
        summary: >-
          HAProxy: {{ $labels.frontend }} frontend experienced {{ $value }}% increase in client errors over the last 5
          minutes
        description: >-
          blah blah blah