apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: haproxy-ingress.rules
  namespace: monitoring
spec:
# Info and advice obtained from https://www.datadoghq.com/blog/monitoring-haproxy-performance-metrics
  groups:
  - name: haproxy-ingress.rules
    rules:

    # Join labels and register resultant datasets
    - record: haproxy:http_backend_response_wait_seconds_bucket:labeled
      expr: |
        label_replace(
          label_replace(http_backend_response_wait_seconds_bucket{backend!~"(error|stats|httpback|upstream).*"}, "joiner", "$1", "backend", "(.*)-\\d+$")
            * on(joiner) group_left(label_app_kubernetes_io_owner)
            label_join(kube_service_labels, "joiner", "-", "namespace", "service"),
          "label_app_kubernetes_io_owner",
          "satoshi",
          "label_app_kubernetes_io_owner",
          ""
        )

    - record: haproxy:http_backend_queue_time_seconds_bucket:labeled
      expr: |
        label_replace(
          label_replace(http_backend_queue_time_seconds_bucket{backend!~"(error|stats|httpback|upstream).*"}, "joiner", "$1", "backend", "(.*)-\\d+$")
            * on(joiner) group_left(label_app_kubernetes_io_owner)
            label_join(kube_service_labels, "joiner", "-", "namespace", "service"),
          "label_app_kubernetes_io_owner",
          "satoshi",
          "label_app_kubernetes_io_owner",
          ""
        )

    - record: haproxy:haproxy_backend_current_queue:labeled
      expr: |
        label_replace(
          label_replace(haproxy_backend_current_queue{backend!~"(error|stats|httpback|upstream).*"}, "joiner", "$1", "backend", "(.*)-\\d+$")
            * on(joiner) group_left(label_app_kubernetes_io_owner)
            label_join(kube_service_labels, "joiner", "-", "namespace", "service"),
          "label_app_kubernetes_io_owner",
          "satoshi",
          "label_app_kubernetes_io_owner",
          ""
        )

    - record: haproxy:haproxy_backend_response_errors_total:labeled
      expr: |
        label_replace(
          label_replace(haproxy_backend_response_errors_total{backend!~"(error|stats|httpback|upstream).*"}, "joiner", "$1", "backend", "(.*)-\\d+$")
            * on(joiner) group_left(label_app_kubernetes_io_owner)
            label_join(kube_service_labels, "joiner", "-", "namespace", "service"),
          "label_app_kubernetes_io_owner",
          "satoshi",
          "label_app_kubernetes_io_owner",
          ""
        )

    - record: haproxy:haproxy_backend_http_responses_total:labeled
      expr: |
        label_replace(
          label_replace(haproxy_backend_http_responses_total{backend!~"(error|stats|httpback|upstream).*"}, "joiner", "$1", "backend", "(.*)-\\d+$")
            * on(joiner) group_left(label_app_kubernetes_io_owner)
            label_join(kube_service_labels, "joiner", "-", "namespace", "service"),
          "label_app_kubernetes_io_owner",
          "satoshi",
          "label_app_kubernetes_io_owner",
          ""
        )

    - record: haproxy:haproxy_backend_up:labeled
      expr: |
        label_replace(
          label_replace(haproxy_backend_up{backend!~"(error|stats|httpback|upstream).*"}, "joiner", "$1", "backend", "(.*)-\\d+$")
            * on(joiner) group_left(label_app_kubernetes_io_owner)
            label_join(kube_service_labels, "joiner", "-", "namespace", "service"),
          "label_app_kubernetes_io_owner",
          "satoshi",
          "label_app_kubernetes_io_owner",
          ""
        )

    # Set 95th percentiles for response time and queue wait time
    - record: haproxy:http_backend_response_wait_seconds_bucket:histogram_quantile
      expr: |
        histogram_quantile(0.95, sum(rate(http_backend_response_wait_seconds_bucket[5m])) by (backend, le, label_app_kubernetes_io_owner))
      labels:
        quantile: "0.95"

    - record: haproxy:http_backend_queue_time_seconds_bucket:histogram_quantile
      expr: |
        histogram_quantile(0.95, sum(rate(http_backend_queue_time_seconds_bucket[5m])) by (backend, le, label_app_kubernetes_io_owner))
      labels:
        quantile: "0.95"

    # Frontend Session Usage (% of limit) | Warning
    - alert: HAProxyFrontendSessionUsage
      expr: >-
        sum by (frontend) (haproxy_frontend_current_sessions)
        / sum by (frontend) (haproxy_frontend_limit_sessions)
        * 100 >= 80
      labels:
        severity: warning
      annotations:
        summary: "HAProxy: Session usage on {{ $labels.frontend }} frontend has reached {{ $value }}%"
        runbook_url: https://gitlab.com/mintel/satoshi/monitoring/runbooks/blob/master/satoshi/platform/HAProxy.md#HAProxyFrontendSessionUsage

    # Frontend Session Usage (% of limit) | Critical
    - alert: HAProxyFrontendSessionUsage
      expr: >-
        sum by (frontend) (haproxy_frontend_current_sessions)
        / sum by (frontend) (haproxy_frontend_limit_sessions)
        * 100 >= 90
      labels:
        severity: critical
      annotations:
        summary: "HAProxy: Session usage on {{ $labels.frontend }} frontend has reached {{ $value }}%"
        runbook_url: https://gitlab.com/mintel/satoshi/monitoring/runbooks/blob/master/satoshi/platform/HAProxy.md#HAProxyFrontendSessionUsage

    # Frontend Request Denied not required. No ACLs currently configured in HAProxy.

    # Frontend Request Errors (% of total requests) | Warning
    - alert: HAProxyFrontendRequestErrors
      expr: >-
        sum by (frontend) (rate(haproxy_frontend_request_errors_total[1m]))
        / sum by (frontend) (rate(haproxy_frontend_http_requests_total[1m])) * 100 > 1
      for: 3m
      labels:
        severity: warning
      annotations:
        summary: "HAProxy: Request error rate increase detected on {{ $labels.frontend }} frontend"
        runbook_url: https://gitlab.com/mintel/satoshi/monitoring/runbooks/blob/master/satoshi/platform/HAProxy.md#HAProxyFrontendRequestErrors

    # Frontend Request Errors (% of total requests) | Critical
    - alert: HAProxyFrontendRequestErrors
      expr: >-
        sum by (frontend) (rate(haproxy_frontend_request_errors_total[1m]))
        / sum by (frontend) (rate(haproxy_frontend_http_requests_total[1m])) * 100 > 5
      for: 3m
      labels:
        severity: critical
      annotations:
        summary: "HAProxy: Request error rate increase detected on {{ $labels.frontend }} frontend"
        runbook_url: https://gitlab.com/mintel/satoshi/monitoring/runbooks/blob/master/satoshi/platform/HAProxy.md#HAProxyFrontendRequestErrors

    # No. of Request in Backend Queue | Warning
    - alert: HAProxyBackendRequestQueued
      expr: >-
        sum by (backend, label_app_kubernetes_io_owner) (haproxy:haproxy_backend_current_queue:labeled) > 10
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "HAProxy: Request are queuing up on the {{ $labels.backend }} backend"
        runbook_url: https://gitlab.com/mintel/satoshi/monitoring/runbooks/blob/master/satoshi/platform/HAProxy.md#HAProxyBackendRequestQueued

    # No. of Request in Backend Queue | Critical
    - alert: HAProxyBackendRequestQueued
      expr: >-
        sum by (backend, label_app_kubernetes_io_owner) (haproxy:haproxy_backend_current_queue:labeled) > 100
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "HAProxy: Request are queuing up on the {{ $labels.backend }} backend"
        runbook_url: https://gitlab.com/mintel/satoshi/monitoring/runbooks/blob/master/satoshi/platform/HAProxy.md#HAProxyBackendRequestQueued

    # Average Time Spent in Backend Queue | Warning
    - alert: HAProxyBackendRequestQueuedTime
      expr: >-
        haproxy:http_backend_queue_time_seconds_bucket:histogram_quantile > 0.1
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "HAProxy: Excessive request queue time on the {{ $labels.backend }} backend"
        runbook_url: https://gitlab.com/mintel/satoshi/monitoring/runbooks/blob/master/satoshi/platform/HAProxy.md#HAProxyBackendRequestQueuedTime

    # Average Time Spent in Backend Queue | Critical
    - alert: HAProxyBackendRequestQueuedTime
      expr: >-
        haproxy:http_backend_queue_time_seconds_bucket:histogram_quantile > 0.5
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "HAProxy: Excessive request queue time on the {{ $labels.backend }} backend"
        runbook_url: https://gitlab.com/mintel/satoshi/monitoring/runbooks/blob/master/satoshi/platform/HAProxy.md#HAProxyBackendRequestQueuedTime

    # Average Backend Response Time | Warning
    - alert: HAProxyBackendResponseTime
      expr: >-
        haproxy:http_backend_response_wait_seconds_bucket:histogram_quantile > 0.5
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "HAProxy: Average response times increased on {{ $labels.backend }} backend"
        runbook_url: https://gitlab.com/mintel/satoshi/monitoring/runbooks/blob/master/satoshi/platform/HAProxy.md#HAProxyBackendResponseTime

    # Average Backend Response Time | Critical
    - alert: HAProxyBackendResponseTime
      expr: >-
        haproxy:http_backend_response_wait_seconds_bucket:histogram_quantile > 1
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "HAProxy: Average response times increased on {{ $labels.backend }} backend"
        runbook_url: https://gitlab.com/mintel/satoshi/monitoring/runbooks/blob/master/satoshi/platform/HAProxy.md#HAProxyBackendResponseTime

    # No. of Backend Response Errors | Warning
    - alert: HAProxyBackendResponseErrors
      expr: >-
        sum by (backend, label_app_kubernetes_io_owner) (rate(haproxy:haproxy_backend_response_errors_total:labeled[1m])) > 1
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "HAProxy: Response errors detected on {{ $labels.backend }} backend"
        runbook_url: https://gitlab.com/mintel/satoshi/monitoring/runbooks/blob/master/satoshi/platform/HAProxy.md#HAProxyBackendResponseErrors

    # No. of Backend Response Errors | Critical
    - alert: HAProxyBackendResponseErrors
      expr: >-
        sum by (backend, label_app_kubernetes_io_owner) (rate(haproxy:haproxy_backend_response_errors_total:labeled[1m])) > 10
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "HAProxy: Response errors detected on {{ $labels.backend }} backend"
        runbook_url: https://gitlab.com/mintel/satoshi/monitoring/runbooks/blob/master/satoshi/platform/HAProxy.md#HAProxyBackendResponseErrors

    # Percentage of HTTP responses that are server errors (5xx) | Warning
    - alert: HAProxyBackendResponseErrors5xx
      expr: >-
        (
          sum by (backend, label_app_kubernetes_io_owner) (rate(haproxy:haproxy_backend_http_responses_total:labeled{code=~"5.."}[1m]))
          /
          sum by (backend, label_app_kubernetes_io_owner) (rate(haproxy:haproxy_backend_http_responses_total:labeled[1m]))
        )
        * 100 > 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "HAProxy: Increased number of 5xx responses on {{ $labels.backend }} service"
        runbook_url: https://gitlab.com/mintel/satoshi/monitoring/runbooks/blob/master/satoshi/platform/HAProxy.md#HAProxyBackendResponseErrors5xx

    # Percentage of HTTP responses that are server errors (5xx) | Critical
    - alert: HAProxyBackendResponseErrors5xx
      expr: >-
        (
          sum by (backend, label_app_kubernetes_io_owner) (rate(haproxy:haproxy_backend_http_responses_total:labeled{code=~"5.."}[1m]))
          /
          sum by (backend, label_app_kubernetes_io_owner) (rate(haproxy:haproxy_backend_http_responses_total:labeled[1m]))
        )
        * 100 > 10
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "HAProxy: Increased number of 5xx responses on {{ $labels.backend }} service"
        runbook_url: https://gitlab.com/mintel/satoshi/monitoring/runbooks/blob/master/satoshi/platform/HAProxy.md#HAProxyBackendResponseErrors5xx

    # Alert if a backend service is down for > 1m
    - alert: HAProxyBackendDown
      expr: sum by (backend, label_app_kubernetes_io_owner) (haproxy:haproxy_backend_up:labeled) == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        description: "HAProxy: {{ $labels.backend }} service has been down for at least 1m"
        runbook_url: https://gitlab.com/mintel/satoshi/monitoring/runbooks/blob/master/satoshi/platform/HAProxy.md#HAProxyBackendDown