---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: haproxy
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      hostNetwork: true
      nodeSelector:
        role: ingress-controller
      serviceAccountName: ingress-controller
      containers:
      - name: haproxy-ingress
        image: quay.io/jcmoraisjr/haproxy-ingress
        args:
        - --default-backend-service=$(POD_NAMESPACE)/ingress-default-backend
        - --configmap=$(POD_NAMESPACE)/haproxy-ingress
        - --sort-backends
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: stat
          containerPort: 1936
        livenessProbe:
          httpGet:
            path: /healthz
            port: 10253
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      - name: haproxy-exporter
        image: quay.io/prometheus/haproxy-exporter:v0.9.0
        args:
        - '--haproxy.scrape-uri=http://localhost:1936/haproxy?stats;csv'
        ports:
        - name: metrics
          containerPort: 9101
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-exporter
  labels:
    app: haproxy
spec:
  selector:
    app: haproxy
  ports:
  - name: metrics
    port: 9101
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-ingress
  labels:
    app: haproxy
spec:
  selector:
    app: haproxy
  ports:
  - name: http
    port: 80
    targetPort: 80
  type: NodePort
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: haproxy
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: haproxy
  endpoints:
  - port: metrics
